# Generated by Django 5.0.6 on 2024-07-31 15:22

import django.db.models.deletion
import parler.fields
import parler.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_image', models.ImageField(blank=True, upload_to='profiles/images/home/', verbose_name='Home image')),
                ('video', models.URLField(blank=True, verbose_name='Video')),
                ('about_image', models.ImageField(blank=True, upload_to='profiles/images/about/', verbose_name='About image')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
                ('birth_day', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated by')),
                ('freelance', models.BooleanField(blank=True, default=False, verbose_name='Freelance')),
                ('tweeter', models.URLField(blank='True', null=True, verbose_name='Tweeter')),
                ('facebook', models.URLField(blank='True', null=True, verbose_name='Facebook')),
                ('linkedin', models.URLField(blank='True', null=True, verbose_name='Linked in')),
                ('instagram', models.URLField(blank='True', null=True, verbose_name='Instagram')),
                ('quality_public', models.BooleanField(default=False, verbose_name='Quality')),
                ('skill_public', models.BooleanField(default=False, verbose_name='Skill')),
                ('service_public', models.BooleanField(default=False, verbose_name='Service')),
                ('portfolio_public', models.BooleanField(default=False, verbose_name='Portfolio')),
                ('review_public', models.BooleanField(default=False, verbose_name='Review')),
                ('blog_public', models.BooleanField(default=False, verbose_name='Blog')),
                ('contact_public', models.BooleanField(default=False, verbose_name='Contact')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProfileTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('home_page_title', models.CharField(blank=True, max_length=200, verbose_name='Home page Title')),
                ('cv', models.FileField(blank=True, upload_to='profiles/documents/cv/', verbose_name='Cv')),
                ('about_me_title', models.CharField(blank=True, max_length=200, verbose_name='About me title')),
                ('summary', models.TextField(blank=True, verbose_name='Summary')),
                ('degree', models.CharField(blank=True, max_length=50, verbose_name='Degree')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Address')),
                ('experience_period', models.CharField(blank=True, help_text='enter digit and years or month example: 10 Years and 3 months', max_length=50, verbose_name='Experience Period')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'Profile Translation',
                'db_table': 'profiles_profile_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
