# Generated by Django 5.1 on 2024-08-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profiletranslation_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletranslation',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='profiles/documents/cv/', verbose_name='Cv'),
        ),
    ]
