# Generated by Django 5.1 on 2024-09-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profiletranslation_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiletranslation',
            name='cv',
        ),
        migrations.AddField(
            model_name='profile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='profiles/documents/cv/', verbose_name='Cv'),
        ),
    ]
